language: csharp
dotnet: 2.2
sudo: required
solution: "./Turnstile/Turnstile.sln"
dist: xenial
install:
  - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./Turnstile/Turnstile.sln
script:
  - dotnet build ./Turnstile/Turnstile.sln
  - dotnet test ./Turnstile/Turnstile.sln
